/**
 * Public API of @praxis/contracts. Deep imports are forbidden
 * (.praxis/architecture.yaml); everything durable goes through this entry.
 */

export const packageName = "@praxis/contracts";

export type {
  EventActor,
  ModelActor,
  SystemActor,
  ToolActor,
  UserActor,
} from "./actor";
export {
  EventActorSchema,
  ModelActorSchema,
  SystemActorSchema,
  ToolActorSchema,
  UserActorSchema,
} from "./actor";
export type {
  ApprovalRequest,
  CapabilityDecision,
  CapabilityGrant,
  CapabilityLease,
  CapabilityRequirement,
  CapabilityScope,
  CapabilityVia,
} from "./capability/capability";
export {
  ApprovalRequestSchema,
  CapabilityDecisionSchema,
  CapabilityGrantSchema,
  CapabilityLeaseSchema,
  CapabilityRequirementSchema,
  CapabilityScopeSchema,
  CapabilityViaSchema,
  normalizeWorkspaceRoot,
  scopeSatisfies,
  workspaceRootCovers,
} from "./capability/capability";
export type { EventEnvelopeBase, SessionEvent } from "./envelope";
export { EVENT_SCHEMA_VERSION, EventEnvelopeBaseSchema, sessionEventSchema } from "./envelope";
export type {
  Challenge,
  ChallengeOutcome,
  ChallengeStatus,
  ChallengeTargetType,
  GoalState,
  HardConstraint,
  Hypothesis,
  HypothesisStatus,
  Observation,
  ObservationSource,
  Plan,
  PlanStatus,
  VerificationOutcome,
  VerificationResult,
} from "./epistemic/epistemic";
export {
  CHALLENGE_OUTCOMES,
  CHALLENGE_STATUSES,
  CHALLENGE_TARGET_TYPES,
  ChallengeSchema,
  ChallengeStatusSchema,
  ChallengeTargetTypeSchema,
  GoalStateSchema,
  HardConstraintSchema,
  HYPOTHESIS_STATUSES,
  HypothesisSchema,
  HypothesisStatusSchema,
  ObservationCoreSchema,
  ObservationSourceSchema,
  PLAN_STATUSES,
  PlanSchema,
  PlanStatusSchema,
  VERIFICATION_OUTCOMES,
  VerificationOutcomeSchema,
  VerificationResultSchema,
} from "./epistemic/epistemic";
export type {
  ChallengeRaisedEvent,
  ChallengeResolvedEvent,
  EpistemicEventType,
  GoalSetEvent,
  HypothesisProposedEvent,
  HypothesisStatusChange,
  HypothesisStatusChangedEvent,
  ObservationRecordedEvent,
  PlanInvalidatedEvent,
  PlanSetEvent,
  VerificationRecordedEvent,
} from "./events/epistemic-events";
export {
  CHALLENGE_RAISED,
  CHALLENGE_RESOLVED,
  ChallengeRaisedEventSchema,
  ChallengeRaisedPayloadSchema,
  ChallengeResolvedEventSchema,
  ChallengeResolvedPayloadSchema,
  EPISTEMIC_EVENT_SCHEMAS,
  EPISTEMIC_EVENT_TYPES,
  GOAL_SET,
  GoalSetEventSchema,
  GoalSetPayloadSchema,
  HYPOTHESIS_PROPOSED,
  HYPOTHESIS_STATUS_CHANGED,
  HYPOTHESIS_STATUS_CHANGES,
  HypothesisProposedEventSchema,
  HypothesisProposedPayloadSchema,
  HypothesisStatusChangedEventSchema,
  HypothesisStatusChangedPayloadSchema,
  HypothesisStatusChangeSchema,
  OBSERVATION_RECORDED,
  ObservationRecordedEventSchema,
  ObservationRecordedPayloadSchema,
  PLAN_INVALIDATED,
  PLAN_SET,
  PlanInvalidatedEventSchema,
  PlanInvalidatedPayloadSchema,
  PlanSetEventSchema,
  PlanSetPayloadSchema,
  VERIFICATION_RECORDED,
  VerificationRecordedEventSchema,
  VerificationRecordedPayloadSchema,
} from "./events/epistemic-events";
export type {
  ModelEventType,
  ModelRequestFailedEvent,
  ModelRequestStartedEvent,
  ModelResponseCompletedEvent,
} from "./events/model-events";
export {
  MODEL_EVENT_TYPES,
  MODEL_REQUEST_FAILED,
  MODEL_REQUEST_STARTED,
  MODEL_RESPONSE_COMPLETED,
  ModelRequestFailedEventSchema,
  ModelRequestFailedPayloadSchema,
  ModelRequestStartedEventSchema,
  ModelRequestStartedPayloadSchema,
  ModelResponseCompletedEventSchema,
  ModelResponseCompletedPayloadSchema,
} from "./events/model-events";
export type {
  SessionCompletedEvent,
  SessionCreatedEvent,
  SessionEventType,
  SessionEventUnion,
  SessionPausedEvent,
  SessionResumedEvent,
  TurnCompletedEvent,
  TurnStartedEvent,
} from "./events/session-events";
export {
  SESSION_COMPLETED,
  SESSION_CREATED,
  SESSION_EVENT_TYPES,
  SESSION_PAUSED,
  SESSION_RESUMED,
  SessionCompletedEventSchema,
  SessionCompletedPayloadSchema,
  SessionCreatedEventSchema,
  SessionCreatedPayloadSchema,
  SessionEventUnionSchema,
  SessionPausedEventSchema,
  SessionPausedPayloadSchema,
  SessionResumedEventSchema,
  SessionResumedPayloadSchema,
  TURN_COMPLETED,
  TURN_STARTED,
  TurnCompletedEventSchema,
  TurnCompletedPayloadSchema,
  TurnStartedEventSchema,
  TurnStartedPayloadSchema,
} from "./events/session-events";
export type {
  ToolAuthorizedEvent,
  ToolEventType,
  ToolFailedEvent,
  ToolIndeterminateEvent,
  ToolProposedEvent,
  ToolReconciledEvent,
  ToolReconciledPayload,
  ToolRejectedEvent,
  ToolStartedEvent,
  ToolSucceededEvent,
} from "./events/tool-events";
export {
  TOOL_AUTHORIZED,
  TOOL_EVENT_TYPES,
  TOOL_FAILED,
  TOOL_INDETERMINATE,
  TOOL_PROPOSED,
  TOOL_RECONCILED,
  TOOL_REJECTED,
  TOOL_STARTED,
  TOOL_SUCCEEDED,
  ToolAuthorizedEventSchema,
  ToolAuthorizedPayloadSchema,
  ToolFailedEventSchema,
  ToolFailedPayloadSchema,
  ToolIndeterminateEventSchema,
  ToolIndeterminatePayloadSchema,
  ToolProposedEventSchema,
  ToolProposedPayloadSchema,
  ToolReconciledEventSchema,
  ToolReconciledPayloadSchema,
  ToolRejectedEventSchema,
  ToolRejectedPayloadSchema,
  ToolStartedEventSchema,
  ToolStartedPayloadSchema,
  ToolSucceededEventSchema,
  ToolSucceededPayloadSchema,
} from "./events/tool-events";
export type {
  CapabilityLeaseId,
  ChallengeId,
  EventId,
  HypothesisId,
  ObservationId,
  PlanId,
  SessionId,
  StepId,
  ToolExecutionId,
  TurnId,
} from "./ids";
export {
  asCapabilityLeaseId,
  asChallengeId,
  asEventId,
  asHypothesisId,
  asObservationId,
  asPlanId,
  asSessionId,
  asStepId,
  asToolExecutionId,
  asTurnId,
  CapabilityLeaseIdSchema,
  ChallengeIdSchema,
  EventIdSchema,
  HypothesisIdSchema,
  ObservationIdSchema,
  PlanIdSchema,
  SessionIdSchema,
  StepIdSchema,
  ToolExecutionIdSchema,
  TurnIdSchema,
} from "./ids";
export type {
  CompletedEvent,
  ModelEvent,
  ModelFinishReason,
  ModelProviderErrorInfo,
  ModelProviderErrorKind,
  ProviderErrorEvent,
  TextDeltaEvent,
  ToolCallDeltaEvent,
  ToolCallEndEvent,
  ToolCallStartEvent,
  UsageEvent,
} from "./model/events";
export {
  CompletedEventSchema,
  MODEL_FINISH_REASONS,
  MODEL_PROVIDER_ERROR_KINDS,
  ModelEventSchema,
  ModelProviderErrorInfoSchema,
  ProviderErrorEventSchema,
  TextDeltaEventSchema,
  ToolCallDeltaEventSchema,
  ToolCallEndEventSchema,
  ToolCallStartEventSchema,
  UsageEventSchema,
} from "./model/events";
export type { ModelProvider } from "./model/provider";
export type {
  AssistantMessage,
  ModelMessage,
  ModelRequest,
  ModelToolDefinition,
  SystemMessage,
  ToolCallRequest,
  ToolResultMessage,
  UserMessage,
} from "./model/request";
export {
  AssistantMessageSchema,
  ModelMessageSchema,
  ModelRequestSchema,
  ModelToolDefinitionSchema,
  SystemMessageSchema,
  ToolCallRequestSchema,
  ToolResultMessageSchema,
  UserMessageSchema,
} from "./model/request";
export type { EventStore } from "./ports/event-store";
export {
  EMPTY_STREAM_HEAD_SEQ,
  EventStoreConflictError,
} from "./ports/event-store";
export type {
  ReconciliationOutcome,
  ToolDefinition,
  ToolExecutionContext,
  ToolExecutionOutcome,
} from "./ports/tool";
export type { SessionEventMigration } from "./replay";
export {
  applyEventMigrations,
  FutureSchemaVersionError,
  InvalidMigrationTableError,
  InvalidReplayEventError,
  migratedSchemaVersion,
  parseReplayEvent,
  parseReplayStream,
  SESSION_EVENT_MIGRATIONS,
} from "./replay";
export type { ToolExecutionStatus } from "./tool-state";
export {
  TOOL_EXECUTION_STATUSES,
  ToolExecutionStatusSchema,
} from "./tool-state";
export type { ToolEffect } from "./tools/tool-effect";
export { TOOL_EFFECTS, ToolEffectSchema } from "./tools/tool-effect";
